// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IBlogPostFields {
  /** Cover Image */
  coverImage?: Asset | undefined;

  /** Slug */
  slug?: string | undefined;

  /** Title */
  title?: string | undefined;

  /** Author */
  author?: string | undefined;

  /** Tags */
  tags?: ITag[] | undefined;

  /** Description */
  description?: string | undefined;

  /** Body */
  body?: Document | undefined;
}

/** Blog post content model */

export interface IBlogPost extends Entry<IBlogPostFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "blog-post";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ICodeBlockFields {
  /** code */
  code?: string | undefined;

  /** language */
  language?: string | undefined;
}

export interface ICodeBlock extends Entry<ICodeBlockFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "codeBlock";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITagFields {
  /** Tag */
  tag?: string | undefined;

  /** Color */
  color?: string | undefined;
}

export interface ITag extends Entry<ITagFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "tag";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "blog-post" | "codeBlock" | "tag";

export type IEntry = IBlogPost | ICodeBlock | ITag;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
